### ISSUE TITLE
Use launch_socket_server instead of a firewall rule

### ISSUE THREAD

**Issue by sstephenson** [puma/puma-dev#1]
Hi @evanphx - happy to see this project underway!

May I suggest using [launch_socket_server](https://github.com/sstephenson/launch_socket_server) instead of a firewall rule to bind to port 80? I designed it to be used with Pow, but never got around to bundling it in an official Pow release.

**Comment by evanphx** [comment]
Hi Sam! Thanks!

Oh, launch_socket_server looks great! Since it's unlikely that people have it installed already, do you think that puma should:

1. Bundle launch_socket_server and install it if it's not otherwise installed.
2. Detect if it's installed and use if it is, otherwise use the firewall rule.

**Comment by sstephenson** [comment]
My suggestion would be to bundle it. Not sure what you had in mind in terms of packaging and installation, but I like [libexec](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html) as a spot for storing private executables:

$PREFIX/bin/puma-dev
$PREFIX/libexec/puma-dev/launch-socket-server

**Comment by evanphx** [comment]
@sstephenson Hi Sam, I took a slightly different approach. Because you figured out all the work for how to make launchd sockets work in Go I just pulled that functionality directly into puma-dev! One fewer thing to run then because I can wire `net/http` directly up to the launchd socket!

Even better, I found out that you can listen on privileged ports from user LaunchAgents! So the whole puma-dev installation no longer requires any root access!
