### ISSUE TITLE
Support for direnv

### ISSUE THREAD

**Issue by sudostack** [puma/puma-dev#116]
This is an enhancement request. I'm not sure how popular it is. I've moved away from using dotenv a year ago and currently use [direnv](https://github.com/direnv/direnv) and like it much more, but I still do a ton of Rails development still and would love for puma-dev to pick up the `export`s in my `.envrc`. 

I don't develop in Golang at all, but believe I know where to introduce a change and could submit a PR. Thoughts?

**Comment by sudostack** [comment]
Closing thanks to @zimbatm

**Comment by mislav** [comment]
Noting for posterity: I'm a direnv user and puma-dev didn't work with my project until I used a puma-specific workaround, but that workaround is different than what @zimbatm suggested above. I'm sharing the workaround in case it helps anyone searching for this.

I do not have static environment variables, but instead I use [the direnv stdlib](https://direnv.net/man/direnv-stdlib.1.html) to compute environment such as PATH and GEM_HOME for me:
```
$ cat .envrc
load_prefix /opt/homebrew/opt/ruby@3.0
layout ruby
```

Because of this approach, it isn't feasible that I move this configuration over to an `.env` file with static values. Instead, I followed @e28eta's [solution here](https://github.com/e28eta/e28eta.github.io/commit/c1ac66d27b5cea46b9530e543006cc79b55be127) and created an additional `.pumaenv` file for the project that "sources" the `.envrc`:
```
$ cat .pumaenv 
eval "$(direnv export bash)"
```

I would add my vote for built-in support for direnv within puma-dev, but in the meantime, this demonstrates it's possible to add a shell hook that eval's direnv per-project configuration.

Thank you both puma-dev devs and direnv devs! 🙏
