### ISSUE TITLE
Building puma-dev locally for development fails

### ISSUE THREAD

**Issue by thetizzo** [puma/puma-dev#148]
Hi! 

**First a disclaimer**: I'm mostly a Rubyist who's not worked with Go before so I'm sure there is an easy solution here that I'm just not able to figure out through much Googling and issue reading.

I'm attempting to get puma-dev to build on my machine in order to attempt to build some error pages to solve #124.

I've followed the instructions in the README, installed Go and `gb` to build the project and tried several different ways to build it but can't make it build correctly.

When using `make` or `go get github.com/puma/puma-dev/...`, I get this:
```
# github.com/puma/puma-dev/vendor/github.com/fsnotify/fsevents
vendor/github.com/fsnotify/fsevents/fsevents.go:38: constant 36893488147419103231 overflows uint64
vendor/github.com/fsnotify/fsevents/fsevents.go:240: constant 36893488147419103231 overflows C.FSEventStreamEventId
```

Using `gb build cmd/puma-dev` from the project directory gives this:
```
FATAL: command "build" failed: failed to resolve import path "github.com/puma/puma-dev/cmd/puma-dev": import "github.com/bmizerany/pat": not found: stat $HOME/go/src/github.com/bmizerany/pat: no such file or directory
```

Can anyone help me with the solution for this? I would love to contribute to this project since I use it for my daily development of Rails apps.

My environment is:
macOS Sierra 10.12.6
go version go1.9.2 darwin/amd64

Thanks!

**Comment by BryanH** [comment]
It looks like the author hard-coded their own environment into the build files instead of making it agnostic. You will need to set up your file locations the same way.

What you have to do is 

1. Find out where the go environment is:

`go env`

Look for the line that shows Go's root. In my case: `GOROOT="/opt/local/lib/go"`. 

1. cd to the GOROOT directory
1. `mkdir -p src/github.com/puma && cd $_` (Note: you may have to sudo to create these directories and make whatever permission changes necessary to be able to write into them)
1. Put the `puma-dev` directory you checked out from this github into the `puma` directory.
1. `cd puma-dev`
1. `make`

If it works, congrats! 

If, instead, it complains that "constant ... overflows uint64" then welcome to go-hell.

**Comment by thetizzo** [comment]
Good news! It turns out that downgrading to Go v1.8.5 solves this build issue.

Sorry for the issue churn.

**Comment by mlarraz** [comment]
This should be addressed by https://github.com/puma/puma-dev/pull/154
