### ISSUE TITLE
Is this a dead project?

### ISSUE THREAD

**Issue by exactchange** [puma/puma-dev#193]
Nobody is replying the many issues having trouble getting puma to work. Is the project being maintained by anyone?

In my case, `puma-dev -install -d localhost` just does not work. 

```
puma-dev -install -d localhost
* Installed puma-dev on ports: http 80, https 443
puma-dev
* Domains: test
* DNS Server port: 9253
* HTTP Server port: 9280
* HTTPS Server port: 9283
! Puma dev listening on http and https
```

^ See how it doesn't set domain or ports? Still defaults to `test`, `9280`, `9283`.

If I run it manually every time like this:

`puma-dev -d localhost -http-port 80 -https-port 443` then it works, but I need it to be configured to use those as defaults.

**Comment by lazyatom** [comment]
I believe in this case, you're doing two separate things:

* `puma-dev -install -d localhost` is installing a `launchd` service configured to use the domains that you want
* `puma-dev` (no arguments) doesn't "re-use" that configuration, since it's only stored in the `launchd` service. Instead, this runs a separate, non-daemonised process. So, as you've seen, if you want to use something other than the defaults, you'll need to provide those options again.

Hopefully that clarifies what's going on. I'd suggest that if you don't want to run the background process, you don't run the `puma-dev -install` command, and instead create a shell alias to run `puma-dev` with the command-line options. If you _are_ happy with the background process, then you don't need to run `puma-dev` again.

**Comment by exactchange** [comment]
Thanks for your reply! I didn't know that it installs a background service. I'm pretty sure the `launchd` service never runs because `ps auwx` doesn't show it running, so I have to run `puma-dev -d localhost -http-port 80 -https-port 443` every time manually before starting my server, then it appears to work. Not ideal, but it works.
