### ISSUE TITLE
bundle: not found

### ISSUE THREAD

**Issue by davekaro** [puma/puma-dev#53]
Similar to #25 perhaps, but after I installed (for the first time) puma-dev and try to get the app launched, I see `bash: line 18: exec: bundle: not found` in the ~/Library/Logs/puma-dev.log file.

I use zsh, with https://github.com/postmodern/chruby and have

```
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh
```

in my ~/.zshrc to load up the correct PATH for my ruby version. Any ideas how to resolve?

**Comment by davekaro** [comment]
I created `.powenv` in the root of my project directory with contents:

```
source /usr/local/share/chruby/chruby.sh
chruby $(cat .ruby-version)
```

Now it works. This makes sense, but is it expected?

**Comment by evanphx** [comment]
Do you have zsh set as your default shell? If not, that's the reason chruby
wasn't picked up. Using .powenv is the right way to handle the issue.

**Comment by davekaro** [comment]
Yes zsh is my default shell. Are you saying it should pick up chruby if zsh is my default shell? Or I still need to use .powenv/.powrc/etc.?

**Comment by evanphx** [comment]
it should pick up your chruby config from `~/.zshrc` but using `.powenv` like that is exactly what it's for anyway. 

In your terminal, what is the output of `$SHELL`?

**Comment by davekaro** [comment]
```
echo $SHELL
/bin/zsh
```

I'll try to do some more testing on my side. I had a coworker with similar setup try to install puma-dev and he ran in to the same error. So I'm not sure if we both have something misconfigured around our shell or PATH or other. But for now we are using `.powenv` with success.

**Comment by evanphx** [comment]
Ok, I see the issue. chruby's `auto.sh` hooks into the zsh via `preexec_functions` https://github.com/postmodern/chruby/blob/master/share/chruby/auto.sh#L27-L30.

puma-dev does execute your shell in the current directory and load your `~/.zshrc` but it immediately switches to bash to deal with non-bash shells like fish. That's why your ruby isn't loaded because the `preexec_functions` are not run or don't modify the environment variables to a sufficient degree.

The long and short of it is that you'll need to use `.powenv` to achieve what you want because of how chruby works.

**Comment by chadbb** [comment]
> I created `.powenv` in the root of my project directory with contents:
> 
> ```
> source /usr/local/share/chruby/chruby.sh
> chruby $(cat .ruby-version)
> ```
> 
> Now it works. This makes sense, but is it expected?

if you're on an arm based mac update the example with this source path
`source /usr/local/share/chruby/chruby.sh`
